name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Configura o repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Instala dependências e faz o build
      - name: Build with Maven
        run: mvn clean install

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Configura o repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Executa os testes
      - name: Run tests with Maven
        run: mvn test
